Added put method
BaSP-a2022/alfon-a-trackgenix-server pull request #10
Opened 2022-10-10 19:33 UTC by silveriac

2022-10-11 02:45 UTC, LucianaPrat commented on src/resources/tasks.js
> +        return res.status(404).json({
Return would not be needed

2022-10-11 02:45 UTC, LucianaPrat commented on src/resources/tasks.js
> +            console.log(err);
Remove console.log

2022-10-11 03:02 UTC, silveriac commented on src/resources/tasks.js
> +        return res.status(404).json({
Return is needed to break out of the function, if it isn't there you'd get the error about sending responses twice

2022-10-12 14:51 UTC, nicolasblasco requested changes

2022-10-12 14:51 UTC, nicolasblasco commented on src/resources/tasks.js
> +const tasks = require('../data/tasks.json');
We should use import for libraries

2022-10-12 14:51 UTC, nicolasblasco commented on src/resources/tasks.js
> +router.use(express.urlencoded({extended: false}));
We should move this to index.js

2022-10-12 14:51 UTC, nicolasblasco commented on src/resources/tasks.js
> +router.put('/put/', (req, res) =>{
The route should be / because the method already specifies the action of updating

2022-10-12 14:51 UTC, nicolasblasco commented on src/resources/tasks.js
> +module.exports = router;
When using import this should change to export default

2022-10-13 00:56 UTC, nicolasblasco approved these changes

2022-10-13 00:56 UTC, merged