BaSP-TG: GET and POST methods for Admins
BaSP-a2022/alfon-a-trackgenix-server pull request #14
Opened 2022-10-11 03:05 UTC by FranciscoSantar

Added GET and POST for the admins of Trackgenix

2022-10-11 21:04 UTC, joryapur reviewed
I think everything is very good, clear and concise. Good job mate

2022-10-12 14:29 UTC, nicolasblasco requested changes

2022-10-12 14:29 UTC, nicolasblasco commented on src/resources/admins.js
> +const fs = require('fs');
We should use import to import libraries

2022-10-12 14:29 UTC, nicolasblasco commented on src/resources/admins.js
> +router.get('/getAll', (req, res) => {
The route should be / because the method gets all admins

2022-10-12 14:29 UTC, nicolasblasco commented on src/resources/admins.js
> +router.get('/get/:id', (req, res) => {
The route should be /:id because the method gets the admin by id

2022-10-12 14:29 UTC, nicolasblasco commented on src/resources/admins.js
> +router.get('/getByUsername/:username', (req, res) => {
The route should be /:username because the method gets the admin by username

2022-10-12 14:29 UTC, nicolasblasco commented on src/resources/admins.js
> +  fs.writeFile('src/data/admins.json', JSON.stringify(admins, null, 4), (err) => {
The third parameter of the JSON.stringify() should be 2 because the rest of the team uses it with this value.

2022-10-12 14:29 UTC, nicolasblasco commented on src/resources/admins.js
> +        msg: 'There was an error',
We should remove this message following the criteria of the team

2022-10-12 14:29 UTC, nicolasblasco commented on src/resources/admins.js
> +module.exports = router;
When using import this should change to export default

2022-10-13 20:38 UTC, merged