BaSP-TG: Added get super admins list
BaSP-a2022/alfon-a-trackgenix-server pull request #16
Opened 2022-10-11 19:14 UTC by LucianaPrat

Added method to get super admins, filtering by first name.
[localhost:3000/super-admins/filter?firstName=Effie](http://localhost:3000/super-admins/filter?firstName=Effie)

2022-10-11 21:09 UTC, joryapur reviewed
I think everything is fine! Thank you for doing the group work and collaborating

2022-10-12 14:10 UTC, nicolasblasco requested changes

2022-10-12 14:10 UTC, nicolasblasco commented on src/resources/super-admins.js
> +router.get('/filter', (req, res) => {
We should change the route to /:firstName

2022-10-12 14:10 UTC, nicolasblasco commented on src/resources/super-admins.js
> +    res.status(200).send({ success: true, msg: 'Super Admin found successfully', data: foundSuperAdmins });
The response should send JSON instead of send

2022-10-12 14:10 UTC, nicolasblasco commented on src/resources/super-admins.js
> +    res.status(404).send({ success: false });
Same as above

2022-10-12 14:39 UTC, nicolasblasco requested changes

2022-10-13 15:21 UTC, nicolasblasco approved these changes

2022-10-13 15:21 UTC, merged