BaSP-TG-5: Update and delete employees
BaSP-a2022/alfon-a-trackgenix-server pull request #20
Opened 2022-10-16 22:13 UTC by FranciscoSantar

Made the Delete and Update actions for the employees in the database

2022-10-16 23:35 UTC, joryapur reviewed
Just that comment that I left you in the code to see how we do it. A pleasure to work together!! thankssss

2022-10-16 23:35 UTC, joryapur commented on src/routes/employees.js
> +import validateCreation from '../validations/employees';
On line 2 employeesControllers is misspelled, I say so that later there are no conflicts.
On line 3 I think maybe it would be better to import it as `import employeesValidations from '../validations/employees';`  I don't know, I imagine that if we had other functions in validations we could export everything at once. but if you think it's better like that I change it in my code so we have the same

2022-10-16 23:35 UTC, joryapur commented on src/routes/employees.js
> +import validateCreation from '../validations/employees';
Now that I think about it, there you are importing all validations as well. The problem would only be the different name, which one do we leave?

2022-10-18 18:19 UTC, nicolasblasco requested changes
We should also add the user validation from this [pull request](https://github.com/BaSP-a2022/alfon-a-trackgenix-server/pull/22)

2022-10-18 18:19 UTC, nicolasblasco commented on src/controllers/employees.js
> +    const result = await Employee.findByIdAndDelete(idEmployee);
We could rename the variable to deletedEmployee

2022-10-18 18:19 UTC, nicolasblasco commented on src/controllers/employees.js
> +    return res.status(200).json({
We should return **res.status(204)** and without the .json()

2022-10-18 18:19 UTC, nicolasblasco commented on src/controllers/employees.js
> +    return res.status(400).json({
The status code should be 500 as its an error from the server

2022-10-18 18:19 UTC, nicolasblasco commented on src/controllers/employees.js
> +    const result = await Employee.findByIdAndUpdate(
We could rename the variable to updatedEmployee

2022-10-18 18:19 UTC, nicolasblasco commented on src/controllers/employees.js
> +      message: `The Employee with the id ${idEmployee} was edited successfully`,
We could replace the word edited to updated

2022-10-18 18:19 UTC, nicolasblasco commented on src/controllers/employees.js
> +    return res.status(400).json({
The status code should be 500 as its an error from the server

2022-10-18 18:22 UTC, nicolasblasco commented on src/controllers/employees.js
> +const editEmployee = async (req, res) => {
We should rename this function to updateEmployee

2022-10-18 22:36 UTC, nicolasblasco approved these changes

2022-10-18 23:37 UTC, nicolasblasco approved these changes

2022-10-18 23:39 UTC, merged