BaSP-TG-2: Get and create admins
BaSP-a2022/alfon-a-trackgenix-server pull request #22
Opened 2022-10-17 00:59 UTC by silveriac

Get and create methods for admin users

2022-10-17 16:19 UTC, nicolasblasco requested changes

2022-10-17 16:19 UTC, nicolasblasco commented on src/validations/user.js
> +        'string.max': 'first name should have a maximum length of 30 characters',
The empty and required message should be the same

2022-10-17 16:19 UTC, nicolasblasco commented on src/validations/user.js
> +      }),
Same as above

2022-10-17 16:19 UTC, nicolasblasco commented on src/validations/user.js
> +      }),
Same as above

2022-10-17 16:19 UTC, nicolasblasco commented on src/validations/user.js
> +      }),
Same as above

2022-10-17 16:19 UTC, nicolasblasco commented on src/models/Admins.js
> +  location: { type: String, required: true },
Phone and location shouldn't be required

2022-10-17 16:19 UTC, nicolasblasco commented on src/controllers/admins.js
> +    if (!admins[0]) {
The condition should be if(!admins)

2022-10-17 16:19 UTC, nicolasblasco commented on src/controllers/admins.js
> +    const admin = await Admins.findById(req.params.id);
We should validate that the id is a valid object id

2022-10-17 16:24 UTC, nicolasblasco commented on src/controllers/admins.js
> +      error,
We could use the message to show all the message, like message: `Unexpected error ${error}`

2022-10-17 16:24 UTC, nicolasblasco commented on src/controllers/admins.js
> +      error,
Same as other comment

2022-10-17 17:22 UTC, silveriac commented on src/controllers/admins.js
> +    if (!admins[0]) {
Alternatively, I can use `if (admins.length == 0)`

2022-10-17 17:59 UTC, silveriac commented
First two commits are  wrongly numbered

2022-10-18 03:12 UTC, Alfondalix approved these changes

2022-10-18 03:13 UTC, merged