BaSP-TG-6: Get and create projects
BaSP-a2022/alfon-a-trackgenix-server pull request #23
Opened 2022-10-17 01:54 UTC by LucianaPrat

Implementation of methods:
-Get project by Id.
-Get list of projects.
-Create a new project.

2022-10-18 18:35 UTC, nicolasblasco requested changes

2022-10-18 18:35 UTC, nicolasblasco commented on src/models/Projects.js
> +      max: 1000,
We shouldn't add validations in the schema

2022-10-18 18:35 UTC, nicolasblasco commented on src/validations/projects.js
> +    rate: Joi.number()
We should add a max and min to the rates number validation. 
Check the documentation here: 

- [validate minimum number](https://joi.dev/api/?v=17.6.1#numberlesslimit)
- [validate maximum number](https://joi.dev/api/?v=17.6.1#numbermaxlimit)

2022-10-18 18:35 UTC, nicolasblasco commented on src/models/Projects.js
> +    rol: { type: String, enum: ['DEV', 'TL', 'QA'] },
We should add the role PM

2022-10-18 18:35 UTC, nicolasblasco commented on src/validations/projects.js
> +        'string.base': 'the rol is not valid',
We should specify the roles that can be valid

2022-10-18 18:35 UTC, nicolasblasco commented on src/validations/projects.js
> +      message: `There was a validation error: ${validation.error.details[0].message} `,
We should use **validation.errors.details** so we can return more than one error

2022-10-18 18:35 UTC, nicolasblasco commented on src/controllers/projects.js
> +        msg: `Couldnt find project with id ${id}`,
Couldn't is mispelled and msg should be message

2022-10-18 18:35 UTC, nicolasblasco commented on src/controllers/projects.js
> +      msg: 'Project found succesfully',
msg should be message

2022-10-18 18:35 UTC, nicolasblasco commented on src/controllers/projects.js
> +      msg: 'An error ocurred',
msg should be message and we should return the error in the message. Like this message: error

2022-10-18 18:35 UTC, nicolasblasco commented on src/controllers/projects.js
> +    return res.status(400).json({
The status code should be 500

2022-10-18 18:35 UTC, nicolasblasco commented on src/controllers/projects.js
> +      teamMembers: req.body.teamMembers,
We could directly do Projects(req.body)

2022-10-18 18:35 UTC, nicolasblasco commented on src/controllers/projects.js
> +      data: undefined,
We should add message: error

2022-10-18 18:35 UTC, nicolasblasco commented on src/controllers/projects.js
> +    const result = await newProject.save();
We could rename this variable to newProjectSaved

2022-10-18 18:59 UTC, nicolasblasco commented on src/controllers/projects.js
> +    return false;
This function should go above all the controlllers

2022-10-19 19:03 UTC, Alfondalix approved these changes

2022-10-19 19:03 UTC, merged