TG: added the getById request
BaSP-a2022/alfon-a-trackgenix-server pull request #3
Opened 2022-10-09 06:24 UTC by MaicolFreire001

Timesheets

http://localhost:3000/time-sheets/getById/:id

Implemented the GET request to obtain a timesheet by its id.

2022-10-10 14:38 UTC, JuanModica reviewed
Everything ok!

2022-10-12 15:32 UTC, nicolasblasco requested changes

2022-10-12 15:32 UTC, nicolasblasco commented on src/resources/time-sheets.js
> +router.get('/getById/:id', (req, res) => {
The route should be /:id because the method with the params already specifies the action of getting a time sheet

2022-10-12 23:40 UTC, Alfondalix approved these changes

2022-10-12 23:40 UTC, merged