TG-23: basic tests
BaSP-a2022/alfon-a-trackgenix-server pull request #40
Opened 2022-10-24 01:54 UTC by silveriac

Only tests for status 200, 204, 400 (only tests one validation) and 404.

2022-10-24 13:53 UTC, MaicolFreire001 requested changes

2022-10-24 13:53 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +const seed = {
We should call this const "mockedProject"

2022-10-24 13:53 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +  });
We could also test if the id is invalid

2022-10-24 13:53 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +  });
We could also test if the id is invalid

2022-10-24 15:39 UTC, silveriac commented on src/test/projects.test.js
> +  });
Are you talking about the returned error message?

2022-10-24 15:41 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +  });
Yes but also a separate test for invalid id and wrong id

2022-10-24 21:58 UTC, silveriac commented on src/test/projects.test.js
> +  });
Agreed. I'll add it

2022-10-25 02:50 UTC, MaicolFreire001 requested changes

2022-10-25 02:50 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +  });
We could add and expect for the message and/or error boolean

2022-10-25 02:50 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +  });
We could add and expect for the message and/or error boolean

2022-10-25 02:50 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +    expect(res.status).toBe(400);
We could add and expect for the message and/or error boolean

2022-10-25 02:50 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +  });
We could add and expect for the error boolean

2022-10-25 02:50 UTC, MaicolFreire001 commented on src/test/projects.test.js
> +  });
We could add and expect for the message and/or error boolean

2022-10-25 23:08 UTC, nicolasblasco requested changes

2022-10-25 23:08 UTC, nicolasblasco commented on src/index.js
> +const port = process.env.PORT || 4000;
We should change the port value

2022-10-25 23:08 UTC, nicolasblasco commented on src/test/projects.test.js
> +    expect(res.status).toBe(200);
We should test the message and the error in the response

2022-10-25 23:08 UTC, nicolasblasco commented on src/test/projects.test.js
> +    expect(res.body.error).toBeTruthy();
We should also test the message of the body in the response

2022-10-25 23:08 UTC, nicolasblasco commented on src/test/projects.test.js
> +    expect(res.body.error).toBeTruthy();
We should also test the message of the body in the response

2022-10-26 23:16 UTC, nicolasblasco approved these changes

2022-10-26 23:17 UTC, MaicolFreire001 approved these changes

2022-10-26 23:18 UTC, merged