BaSP-TG-33: Test Timesheets: put, delete
BaSP-a2022/alfon-a-trackgenix-server pull request #41
Opened 2022-10-24 22:22 UTC by FranciscoSantar

Create Tests units for Update and Delete methods of time sheets route

2022-10-25 03:03 UTC, MaicolFreire001 requested changes

2022-10-25 03:03 UTC, MaicolFreire001 commented on src/test/timesheets.test.js
> +  });
We could do the four expects in the same test

2022-10-25 03:03 UTC, MaicolFreire001 commented on src/test/timesheets.test.js
> +});
We could put the two expects in the same test and also the test names doesn't match

2022-10-25 03:03 UTC, MaicolFreire001 commented on src/test/timesheets.test.js
> +  });
We could do the three expects in the same test

2022-10-25 03:03 UTC, MaicolFreire001 commented on src/test/timesheets.test.js
> +  });
We could do the three expects in the same test and also the test names doesn't match

2022-10-25 23:14 UTC, nicolasblasco requested changes

2022-10-25 23:14 UTC, nicolasblasco commented on src/test/timesheets.test.js
> +    expect(response.body.data.hours).toBe(10);
We should also test the message and the error of the body in the response. And there is no need to test if the data has the correct hours

2022-10-25 23:14 UTC, nicolasblasco commented on src/test/timesheets.test.js
> +    expect(response.body.error).toBeTruthy();
We should also test the message of the body

2022-10-25 23:14 UTC, nicolasblasco commented on src/test/timesheets.test.js
> +    expect(response.body.error).toBeTruthy();
We should also test the message of the body

2022-10-25 23:14 UTC, nicolasblasco commented on src/test/timesheets.test.js
> +    expect(response.body.message).toContain(`${wrongTimeSheetId}`);
We should use the method toBe()

2022-10-25 23:14 UTC, nicolasblasco commented on src/test/timesheets.test.js
> +    expect(response.body.message).toContain(`${fakeTimeSheetId}`);
We should use the method toBe()

2022-10-25 23:14 UTC, nicolasblasco commented on src/test/timesheets.test.js
> +    expect(response.body.message[1].message).toContain('maximum 12 hours');
We should use the method toBe()

2022-10-25 23:14 UTC, nicolasblasco commented on src/test/timesheets.test.js
> +    expect(response.body.data).toBe(undefined);
We could use .not.toBeDefined(). So we use the same method as before to tests for defined and undefined.

2022-10-25 23:14 UTC, nicolasblasco commented on src/test/timesheets.test.js
> +  });
We should also test the error of the body to be true

2022-10-26 23:18 UTC, MaicolFreire001 approved these changes

2022-10-27 02:13 UTC, nicolasblasco approved these changes

2022-10-27 02:13 UTC, merged