Tg 27 test employee put delete
BaSP-a2022/alfon-a-trackgenix-server pull request #42
Opened 2022-10-25 03:30 UTC by Ericks19

Worked testing the endpoints of employee whit methods put and delete

2022-10-25 04:03 UTC, MaicolFreire001 requested changes

2022-10-25 04:03 UTC, MaicolFreire001 commented on src/test/employees.test.js
> +    expect(response.body.data.location).toBe('Miame');
You could make a mocked employee with dni and phone being numbers so you could check the entire body at once

2022-10-25 04:03 UTC, MaicolFreire001 commented on src/test/employees.test.js
> +    const invalidId = 254;
invalidId could be a global variable because is used more than once

2022-10-26 00:24 UTC, nicolasblasco requested changes

2022-10-26 00:24 UTC, nicolasblasco commented on src/test/employees.test.js
> +const employeeIdPeter = '63531244ec6456efd12685ef';
We could rename the variable to firstEmployeeIdFromSeed and get the id like this employeesSeed[0]._id

2022-10-26 00:24 UTC, nicolasblasco commented on src/test/employees.test.js
> +const employeeIdErnesto = '63573014db9ebdd9d24e7b93';
We could rename the variable to secondEmployeeIdFromSeed and get the id like this employeesSeed[1]._id

2022-10-26 00:24 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.message[0].message).toBe('email required');
We should also test the error of the body

2022-10-26 00:51 UTC, Ericks19 commented on src/test/employees.test.js
> +    expect(response.body.message[0].message).toBe('email required');
The error 400 from the validations doesnt throw any error I guess it gives a message and data only

2022-10-26 23:13 UTC, nicolasblasco submitted a review, later dismissed

2022-10-26 23:15 UTC, MaicolFreire001 approved these changes

2022-10-27 01:56 UTC, nicolasblasco approved these changes

2022-10-27 01:56 UTC, merged