BaSP-TG-30: Test Admin: get, getById, post
BaSP-a2022/alfon-a-trackgenix-server pull request #44
Opened 2022-10-25 06:54 UTC by silveriac

2022-10-25 21:05 UTC, MaicolFreire001 requested changes

2022-10-25 21:05 UTC, MaicolFreire001 commented on src/test/admins.test.js
> +  });
We could add expects for error boolean and/or message

2022-10-25 21:05 UTC, MaicolFreire001 commented on src/test/admins.test.js
> +    expect(res.status).toBe(201);
We could add expects for error boolean and/or message

2022-10-25 21:05 UTC, MaicolFreire001 commented on src/test/admins.test.js
> +  });
We could add expects for error boolean and/or message

2022-10-26 11:57 UTC, nicolasblasco requested changes

2022-10-26 11:57 UTC, nicolasblasco commented on src/test/admins.test.js
> +    expect(res.body.error).toBeFalsy();
We should also test the message of the body

2022-10-26 11:57 UTC, nicolasblasco commented on src/test/admins.test.js
> +    expect(res.body.error).toBeFalsy();
We should also test the message of the body

2022-10-26 11:57 UTC, nicolasblasco commented on src/test/admins.test.js
> +    expect(res.body.error).toBeFalsy();
We should also test the message and data of the body

2022-10-26 23:15 UTC, nicolasblasco approved these changes

2022-10-26 23:15 UTC, merged