BaSP-TG-26: Test Employee: get, getById, post
BaSP-a2022/alfon-a-trackgenix-server pull request #45
Opened 2022-10-25 16:02 UTC by JuanModica

testing on GETById employees
testing on POST employees
testing on GET employees

2022-10-25 20:57 UTC, FranciscoSantar commented on package.json
> +    "test": "jest --coverage",
Remember leave onle "jest" when you makethe merge

2022-10-25 21:01 UTC, FranciscoSantar commented on src/test/employees.test.js
> +describe('GETById /employees/:id', () => {
I recomend you to take out the "/:id" on the describe's name, it's not an URL

2022-10-25 23:57 UTC, nicolasblasco requested changes

2022-10-25 23:57 UTC, nicolasblasco commented on src/test/employees.test.js
> +describe('GETById /employees/:id', () => {
I think we should leave it as it describes how the endpoint is used. But I would write it like this: GET /employees/:id

2022-10-25 23:57 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.error).toBeFalsy();
We should also test the message of the body

2022-10-25 23:57 UTC, nicolasblasco commented on src/test/employees.test.js
> +const fixEmployee = employeesSeed.map((employee) => ({
We could rename the variable to formattedEmployeeSeed

2022-10-25 23:57 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.error).toBeTruthy();
We could add the test of the data of the body

2022-10-25 23:57 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.message[0].message).toBe('password required');
We should also test the error of the body

2022-10-25 23:57 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.data.firstName).toEqual(mockedEmployee.firstName);
If we don't test that the whole data is the same, we could omit this test. I suggest that we remove this line.

2022-10-26 02:01 UTC, JuanModica commented on src/test/employees.test.js
> +    expect(response.body.error).toBeTruthy();
the controller doesn't return the data

2022-10-26 02:05 UTC, JuanModica commented on src/test/employees.test.js
> +    expect(response.body.message[0].message).toBe('password required');
in users validation doesn't return an error, should I add it anyway?

2022-10-26 02:07 UTC, JuanModica commented on src/test/employees.test.js
> +    expect(response.body.data.firstName).toEqual(mockedEmployee.firstName);
the three lines or the last?

2022-10-26 02:12 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.error).toBeTruthy();
The controller returns data: undefined. Since we are testing this in other tests, we should do it here too.

2022-10-26 02:13 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.data.firstName).toEqual(mockedEmployee.firstName);
Only line 67

2022-10-26 02:13 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.message[0].message).toBe('password required');
Yes, it does. The validation returns the body with error: true

2022-10-26 02:32 UTC, JuanModica commented on src/test/employees.test.js
> +    expect(response.body.message[0].message).toBe('password required');
in this one when I run the test jest return that the error that the expect receives is undefined

2022-10-26 12:19 UTC, nicolasblasco commented on src/test/employees.test.js
> +    expect(response.body.message[0].message).toBe('password required');
I correct myself. We should test the error, not the error of the body. Becuase the response returns this: 
`return res.status(400).json({
      message: validate.error.details,
      data: undefined,
      error: true,
    });

2022-10-26 14:50 UTC, nicolasblasco approved these changes

2022-10-26 14:50 UTC, merged