BaSP-TG: added create task
BaSP-a2022/alfon-a-trackgenix-server pull request #5
Opened 2022-10-09 19:55 UTC by LucianaPrat

[localhost:3000/tasks/add](http://localhost:3000/tasks/add)

The method to add a task is added. If the fields are empty or one is missing, the task cannot be created.

2022-10-11 15:22 UTC, silveriac commented on src/resources/tasks.js
> +    res.status(400).send({ success: false, msg: 'You must add a description' });
Description may be optional

2022-10-12 15:24 UTC, nicolasblasco commented on src/resources/tasks.js
> +    res.status(400).send({ success: false, msg: 'You must add a description' });
I agree

2022-10-12 15:30 UTC, nicolasblasco requested changes

2022-10-12 15:30 UTC, nicolasblasco commented on src/resources/tasks.js
> +router.post('/add', (req, res) => {
The route should be / because the method already specifies the action of creating

2022-10-12 15:30 UTC, nicolasblasco commented on src/resources/tasks.js
> +const fs = require('fs');
We should use import for libraries

2022-10-12 15:30 UTC, nicolasblasco commented on src/resources/tasks.js
> +  const taskDescription = task.description;
We could directly destructure the task like this: { taskName, taskDescription } = task

2022-10-12 15:30 UTC, nicolasblasco commented on src/resources/tasks.js
> +    res.status(400).send({ success: false, msg: 'You must add name and description' });
We should use res.JSON()

2022-10-12 15:30 UTC, nicolasblasco commented on src/resources/tasks.js
> +    res.status(400).send({ success: false, msg: 'You must add a name' });
Same as above

2022-10-12 15:30 UTC, nicolasblasco commented on src/resources/tasks.js
> +      res.status(500).send({ success: false, msg: 'Cannot save new task' });
Same as above and the status code should be 400

2022-10-12 15:30 UTC, nicolasblasco commented on src/resources/tasks.js
> +      res.status(201).send({ success: true, msg: 'Task Created', data: tasks });
Same as above

2022-10-13 14:58 UTC, nicolasblasco approved these changes

2022-10-13 14:58 UTC, merged