BaSP-TG: project post and delete
BaSP-a2022/alfon-a-trackgenix-server pull request #8
Opened 2022-10-10 13:44 UTC by silveriac

Added post and delete requests for projects

2022-10-10 13:46 UTC, silveriac commented
Esto es un comentario de prueba

2022-10-10 13:53 UTC, nicolasblasco commented on src/resources/projects.js
> +        if(newProject.id && newProject.id == index){
There is no need to send the id when a project is created

2022-10-10 14:12 UTC, silveriac commented on src/resources/projects.js
> +                return res.send("Could not save new project.");
Change responses to res.status

2022-10-11 02:59 UTC, LucianaPrat commented on src/resources/projects.js
> +    else{
Misformatted

2022-10-12 15:06 UTC, nicolasblasco requested changes

2022-10-12 15:06 UTC, nicolasblasco commented on src/resources/projects.js
> +module.exports = router;
We should use export default

2022-10-12 15:06 UTC, nicolasblasco commented on src/resources/projects.js
> +router.delete("/delete/:id", (req, res) => {
The route should be /:id because the method already specifies the action of deleting

2022-10-12 15:06 UTC, nicolasblasco commented on src/resources/projects.js
> +        console.log(newProject[data]);
We should remove this console.log

2022-10-13 00:35 UTC, nicolasblasco approved these changes

2022-10-13 00:35 UTC, merged