TG: work on the PUT request
BaSP-a2022/alfon-a-trackgenix-server pull request #9
Opened 2022-10-10 16:03 UTC by JuanModica

Work on the PUT request of the timesheets.

2022-10-11 09:03 UTC, MaicolFreire001 commented
Everything seems ok!

2022-10-12 14:58 UTC, nicolasblasco requested changes

2022-10-12 14:58 UTC, nicolasblasco commented on src/resources/time-sheets.js
> +const fs = require('fs');
We should use import for libraries

2022-10-12 14:58 UTC, nicolasblasco commented on src/resources/time-sheets.js
> +router.put('/put/:id', (req, res) => {
The route should be /:id because the method with the params already specifies the action of getting a time sheet

2022-10-12 14:58 UTC, nicolasblasco commented on src/resources/time-sheets.js
> +router.delete('/delete/:id', (req, res) => {
The route should be / because the method already specifies the action of getting a time sheet

2022-10-12 14:58 UTC, nicolasblasco commented on src/resources/time-sheets.js
> +module.exports = router;
When using import this should change to export default

2022-10-12 14:58 UTC, nicolasblasco commented on src/resources/time-sheets.js
> +          msg: 'Timesheet id not found',
We should remove this message by following the criteria of the team

2022-10-13 14:00 UTC, nicolasblasco approved these changes

2022-10-13 14:21 UTC, nicolasblasco approved these changes

2022-10-13 14:22 UTC, merged